---
version: '3'
services:
  zookeeper:
    build: .
    image: zhenik/zookeeper-nomad:5.3.1
    environment:
      CONSUL_HTTP_ADDR: "http://172.17.0.1:8500"
      ZOO_LOG4J_PROP: "INFO,CONSOLE"

  zoo1:
    image: zookeeper:3.5.5
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888